services:
  database:
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gymops
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: